version: "3"
networks:
  imagini:
services:
  database:
    image: mysql:5.7
    networks:
      - imagini
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: imagini
      MYSQL_ROOT_PASSWORD: secret
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  service:
    image: imagini:0.0.5
    networks:
      - imagini
    volumes:
      - ${PWD}/settings.json:/opt/app/settings.json
    ports:
      - "80:3000"
    restart: on-failure
